### ISSUE TITLE
How to eject manually

### ISSUE THREAD

**Issue by niqitosiq** [Flyrell/axios-auth-refresh#108]
The documentation doesn't say how to combine
axios-auth-refresh and custom error interceptors.
There is only the line "interceptor id (in case you want to eject it manually)"
How to eject it manually? 
When i use `$axios.onError` (from [@nuxt/axios](https://axios.nuxtjs.org/helpers.html#interceptors)) with `createAuthRefreshInterceptor` it stop working.

Code in nuxtjs plugin file: 
```
import createAuthRefreshInterceptor from 'axios-auth-refresh';
import { Api } from '@/api/api'; // Custom api layer 

export default function({ $axios, store, isServer, res, error }, inject) {
  $axios.onError(async errorObject => {
    const code = parseInt(errorObject.response && errorObject.response.status);
    let message = '';
    if (code === 404) {
      message = 'Page not found';
    }
    if (code === 422) {
      return { error: errorObject, data: errorObject.response.data };
    }
   ... // other codes
    error({ statusCode: code, message }); 

    return { error: errorObject, data: errorObject.response.data };
  });

  const refreshAuthLogic = failedRequest =>
    store.dispatch('global/refreshToken').then(tokenRefreshResponse => {
      failedRequest.response.config.headers['Authorization'] =
        'Bearer ' + tokenRefreshResponse.token;
      return Promise.resolve();
    });

  createAuthRefreshInterceptor($axios, refreshAuthLogic);

  const api = new Api($axios); 
  inject('api', api);

}
```
And it doesn't work, but if remove the onError handler it will

**Comment by Flyrell** [comment]
I'm not exactly sure what you're trying to achieve. Would you please edit your question with a code sample?

**Comment by Flyrell** [comment]
Well I think that in order to propagate the failed response to another interceptor you need to use `Promise.reject(/* ... */)` not just a simple return, as it then think that the error has been handled.

So in your example...
```javascript
$axios.onError(async errorObject => {
    const code = parseInt(errorObject.response && errorObject.response.status);
    let message = '';
    if (code === 404) {
      message = 'Page not found';
    }
    if (code === 422) {
      return Promise.reject({ error: errorObject, data: errorObject.response.data });
    }
   ... // other codes
    error({ statusCode: code, message }); 

    return Promise.reject({ error: errorObject, data: errorObject.response.data });
  });
```

Also, there might be a problem with the order in which the response interceptors are running, if that's the case, try putting the `createAuthRefreshInterceptor` above the `$axios.onError` (I'm not sure about that, just found the old thread for this one: https://github.com/axios/axios/issues/1226)

**Comment by niqitosiq** [comment]
Unfortunately, it didn't help. If I insert the `createAuthRefreshInterceptor` above `onError` handler with `Promise.reject`, it is working the same.
But if I insert it below, it will reproduce the error in browser:
![изображение](https://user-images.githubusercontent.com/15576320/89523857-9f21b580-d7f4-11ea-9e30-c6bd85ce24f7.png)
And no refresh request will sending

**Comment by niqitosiq** [comment]
Maybe I can emit the handler for refresh mannually? Like:
```
$axios.onError(async errorObject => {
    const code = parseInt(errorObject.response && errorObject.response.status);
    let message = '';
    if (code === 404) {
      message = 'Page not found';
    }
    if (code === 401) {
      startAuthRefresh(errorObject);
    }

    error({ statusCode: code, message });

    return Promise.reject({
      error: errorObject,
      data: errorObject.response.data,
    });
  });
```

**Comment by Flyrell** [comment]
Well, if you emit it manually, you woudn't really need that library. But there's a bit more logic for it to work properly, as you need a queue for requests that has been dispatched while the token is refreshing, etc.

I think it might work if you move the `createAuthRefreshInterceptor` above the `onError` (so it gets called after your own `$axios.onError` interceptor and instead of returning `Promise.reject({ error: errorObject, data: errorObject.response.data })` you'd return the `Promise.reject(errorObject);`. Can you try that?

**Comment by niqitosiq** [comment]
Thank you very much! It worked.
