### ISSUE TITLE
unclear documentation

### ISSUE THREAD

**Issue by vtarelkin** [Flyrell/axios-auth-refresh#119]
good day.

It is only me that couldn't get that 

```
axiosInterceptorInstance.interceptors.request.use((request) => {
    request.headers["Authorization"] = `Bearer ${getAccessToken()}`;
    return request;
});
```

apply for ALL request that are made, not only stalling (" to make sure the stalled requests are using the newly fetched data (like token).") but all requests, no need to additionly attach headers to them. It attaches header EVEN to the request that is in the refreshAuthLogic! So in the refreshAuthLogic should be another instance of axios, am I right?

 Also there is no need to write

 `createAuthRefreshInterceptor(axiosInterceptorInstance, refreshAuthLogic);`

in every .js file where we use axios, it spreads all over the project. It will be nice if you provide example with instance like you did in one of the closed PR

It is also unclear why

```
  const refreshAuthLogic = failedRequest => {
    let refreshToken = store.getters['refreshToken'];
    store.dispatch('logout')
    
    return axios.post('/api/token/refresh', {
      refresh_token: refreshToken
    })
      .then(tokenRefreshResponse => {
        store.dispatch('refresh', tokenRefreshResponse)
        failedRequest.response.config.headers['Authorization'] = 'Bearer ' + tokenRefreshResponse.data.token;
        return Promise.resolve()
      })
      .catch(err => {
        console.log(err);
      // redirect to login
      })
```

doesn't trigger at the catch block even if it returns with error. Could you provide some info? 
P.S. it doesn't trigger because there  should be another axios instance. Then it returns errors very well

**Comment by vtarelkin** [comment]
5 days passed, no answer.

**Comment by Flyrell** [comment]
@vtarelkin sorry for not answering. I guess I don't fully understand the issue here. The interceptor is just a suggestion for developers, it's a way of providing all the requests with the newest access token. As your refresh logic can basically be anything (like basic auth, etc.), I don't want to include it into the library as someone might not need it and it would possibly introduce more places for bugs. The naming of the variables in examples is also not something you need to use. It's just to let you know what exactly is represented by the variable.

To answer your question about the catch block not triggering, I will need to take a deeper look at it to find out if that's the bug in the library or it's something that's failing due to the misconfiguration on your side. My guess is it might not be a bug, but we'll see...

After all, it's an open source library, you can always write a PR with suggested changes and I will take my time to look at it and consider merging 🙂

**Comment by sepehr500** [comment]
Heads up. I'm also running into issues with the catch block not returning any errors.
