### ISSUE TITLE
Queued requests when refreshCall fails

### ISSUE THREAD

**Issue by sambrezo** [Flyrell/axios-auth-refresh#14]
I am wondering what happens to queued requests when `refreshCall` is rejected? Looking at the implementation it seems they are kept dangling.

**Comment by Flyrell** [comment]
Yes, you're right. Logic should probably be ran on `finally`. Will fix in the next version with unit tests. Thanks for taking the time! 👍

**Comment by Flyrell** [comment]
I would like to publish it with v1.1.0 (#25) alongside #13 fixes, typescript support and unit tests.

Do you think it'd be enough to run the calls on `.finally` instead of `.then`? I feel like we can do something more sophisticated when the refresh call fails, so the "waiting" requests will not attempt to call the API as it would fail for sure.

**Comment by sambrezo** [comment]
I got somewhat out of the loop on this issue. I would prefer the simple solution with `finally` but I can see why this might not be the best fit for others. Either way, once v1.1.0 is published I will replace my custom solution and report back if any new problems arise.

Thanks for putting in the effort!

**Comment by Flyrell** [comment]
Fixed in #27. Please, give it a try before I publish it as latest release (it's in beta now). 

```
npm install axios-auth-refresh@beta --save
```
