### ISSUE TITLE
Add ability to disable interceptor for specific calls

### ISSUE THREAD

**Issue by Flyrell** [Flyrell/axios-auth-refresh#16]
It would be nice to add the ability to disable interceptor for some of the requests. Right now this is only possible by using multiple instances of the axios. After a [discussion with axios contributors](https://github.com/axios/axios/issues/1890) we know it's possible to add your own properties to the requests' configuration which would enable us to do that.

**Comment by krixon** [comment]
I am actually having an issue which I believe could be resolved with this.

My refresh logic itself issues a request using `axios` - it makes a POST request to exchange a refresh token for a new access token. However this request itself is queued so I the refresh logic promise never resolves.

Unless I am missing something? It seems this would be a pretty common issue but I don't see any reports of it.

**Comment by Flyrell** [comment]
@krixon Wow, you surprised me... this should not be happening at all. Did you try it on the current master? Would you be able to reproduce and share the issue? Thanks.

**Comment by Flyrell** [comment]
Fixed in #27. Please, give it a try before I publish it as latest release (it's in beta now). 

```
npm install axios-auth-refresh@beta --save
```

**Comment by LeoniePhiline** [comment]
Just to confirm, I also ran into this (what @krixon) described.
Going to try the beta now. @Flyrell The TS code looks like **request queue interceptors** are still added unconditionally, aren't they? 

Maybe @krixon is using some Promise/async flow to retrieve the refresh token, before sending the refresh request...

I am using your interceptor to ask the user for a Authenticator one time password via a Quasar Dialog. If the dialog is submittted (not canceled), I try sending a request to laravel to verify the OTP, but the request is stuck in the request queue interceptor. 

The code works for everyone else, because they synchronously send the refresh request before adding the request interceptors (only the response is asynchronous). 
However, I need to wait for the user to enter their OTP and confirm the dialog,  so I'll **asynchronously** fire my request right into the queue and nothing happens any more. Gotta reload. ;)

Probably I need to base my own interceptor on your wonderful work. Thank you in any case!
If you could add a request option to except said request from the queue, that would be grand.

**Comment by krixon** [comment]
Sorry for the late reply.

> Probably I need to base my own interceptor on your wonderful work

This is what I did in the end as I had to move on quickly. I added the ability to provide a whitelist of endpoint uri patterns and avoided queueing matching requests, which is pretty simplistic but enough for my use case.

**Comment by Flyrell** [comment]
@krixon in `@beta` version you should be able to just add `skipAuthRefresh` property to your request object and the interceptor won't be triggered at all. Give it a try if you have some time, I'd use some beta testers for sure 😜 

This should also work for you @LeoniePhiline if I understand your issue correctly, just add the property to the call that shouldn't be queued (well... it won't be intercepted at all if it's not a problem).
