### ISSUE TITLE
Trying to get axios-auth-refresh working with NodeJS

### ISSUE THREAD

**Issue by wipash** [Flyrell/axios-auth-refresh#72]
I'm trying to get axios-auth-refresh working on a small NodeJS app that I'm writing, but as far as I can tell the Axios request isn't continuing after axios-auth-refresh intercepts it.

I'm pretty new to JS development, so not sure if I've missed something obvious. I've looked through the documentation, but can't see any major differences in my implementation.

I'm running Node v13.2.0, v2.2 (latest) of `axios-auth-refresh`, and v0.18.1 of `axios`

My code is as follows:
```javascript
// request.js
require('axios-debug-log');
const axios = require('axios');
const axiosauthrefresh = require('axios-auth-refresh');

const instance = axios.create({
    baseURL: 'https://api.example.com/api/v1.0',
});

let authToken = '';

const refreshAuthLogic = (failedRequest) => {
    console.log('Intercepting auth');
    instance
        .post('/auth/login/', {
            username: process.env.USER,
            password: process.env.PASS,
            skipAuthRefresh: true,
        })
        .then((tokenRefreshResponse) => {
            authToken = tokenRefreshResponse.data.token;
            failedRequest.response.config.headers.Authorization = `Token ${authToken}`;
            console.log(`Auth token: ${authToken}`);
            return Promise.resolve();
        });
};

function getAuthToken() {
    if (authToken) {
        console.log(`Token exists: ${authToken}`);
        return `Token ${authToken}`;
    }
    return null;
}

instance.interceptors.request.use((request) => {
    console.log(`Requesting ${request.url}`);
    const token = getAuthToken();
    if (token) {
        request.headers.Authorization = token;
    }
    return request;
});

axiosauthrefresh.default(instance, refreshAuthLogic);

module.exports = {
    instance,
};
```

I make a request like this:
```javascript
// nmcapi.js
const request= require('./request');
async function GetFolderInfo(volumeID, filerID, path) {
  try {
    const refreshResponse = await request.instance.get(`/volumes/${volumeID}/filers/${filerID}/path/${path}`);
    console.log(`Refresh triggered: ${path}`);
  } catch (error) {
    console.log(error);
  }
}

// interval.js
const nmcapi = require('./nmcapi.js');
const info = await GetFolderInfo('examplevolumeid', 'examplefilerid', 'examplepath')
```

And this is what I get as output:
```
Requesting /volumes/examplevolumeid/filers/examplefilerid/path/examplepath
  axios GET /volumes/examplevolumeid/filers/examplefilerid/path/examplepath +1ms
  axios Error: Request failed with status code 401 (GET https://api.example.com/api/v1.0/volumes/examplevolumeid/filers/examplefilerid/path/examplepath) +265ms
Intercepting auth
Requesting /auth/login/
TypeError: Cannot read property 'then' of undefined
    at f (/home/sean/data-reports/node_modules/axios-auth-refresh/dist/index.min.js:1:1718)
    at /home/sean/data-reports/node_modules/axios-auth-refresh/dist/index.min.js:1:2719
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.GetFolderInfo (/home/sean/data-reports/server/nmcapi.js:29:29)
    at /home/sean/data-reports/server/interval.js:25:18
    at async Promise.all (index 0)
    at Object.intervalFunc (/home/sean/data-reports/server/interval.js:36:18)
  axios POST /auth/login/ +16ms
  axios 200 OK (POST https://api.example.com/api/v1.0/auth/login/) +561ms
Auth token: 17412724ef5169eaab8502a9851480741e606ffa
```
As far as I can tell, the `refreshAuthLogic` function is working properly (because it returns a new auth token), but everything stops after that.

What am I missing?

**Comment by Flyrell** [comment]
Hi, the `refreshAuthLogic` function should return the request `instance.post(...).then(...)`. You're not returning anything it that function, so the library doesn't have any refresh call to bind to.On Jan 8, 2020 20:43, Sean McGrath <notifications@github.com> wrote:I'm trying to get axios-auth-refresh working on a small NodeJS app that I'm writing, but as far as I can tell the Axios request isn't continuing after axios-auth-refresh intercepts it.
I'm pretty new to JS development, so not sure if I've missed something obvious. I've looked through the documentation, but can't see any major differences in my implementation.
I'm running Node v13.2.0, v2.2 (latest) of axios-auth-refresh, and v0.18.1 of axios
My code is as follows:
// request.js
require('axios-debug-log');
const axios = require('axios');
const axiosauthrefresh = require('axios-auth-refresh');

const instance = axios.create({
    baseURL: 'https://api.example.com/api/v1.0',
});

let authToken = '';

const refreshAuthLogic = (failedRequest) => {
    console.log('Intercepting auth');
    instance
        .post('/auth/login/', {
            username: process.env.USER,
            password: process.env.PASS,
            skipAuthRefresh: true,
        })
        .then((tokenRefreshResponse) => {
            authToken = tokenRefreshResponse.data.token;
            failedRequest.response.config.headers.Authorization = `Token ${authToken}`;
            console.log(`Auth token: ${authToken}`);
            return Promise.resolve();
        });
};

function getAuthToken() {
    if (authToken) {
        console.log(`Token exists: ${authToken}`);
        return `Token ${authToken}`;
    }
    return null;
}

instance.interceptors.request.use((request) => {
    console.log(`Requesting ${request.url}`);
    const token = getAuthToken();
    if (token) {
        request.headers.Authorization = token;
    }
    return request;
});

axiosauthrefresh.default(instance, refreshAuthLogic);

module.exports = {
    instance,
};
I make a request like this:
// nmcapi.js
const request= require('./request');
async function GetFolderInfo(volumeID, filerID, path) {
  try {
    const refreshResponse = await request.instance.get(`/volumes/${volumeID}/filers/${filerID}/path/${path}`);
    console.log(`Refresh triggered: ${path}`);
  } catch (error) {
    console.log(error);
  }
}

// interval.js
const nmcapi = require('./nmcapi.js');
const info = await GetFolderInfo('examplevolumeid', 'examplefilerid', 'examplepath')
And this is what I get as output:
Requesting /volumes/examplevolumeid/filers/examplefilerid/path/examplepath
  axios GET /volumes/examplevolumeid/filers/examplefilerid/path/examplepath +1ms
  axios Error: Request failed with status code 401 (GET https://api.example.com/api/v1.0/volumes/examplevolumeid/filers/examplefilerid/path/examplepath) +265ms
Intercepting auth
Requesting /auth/login/
TypeError: Cannot read property 'then' of undefined
    at f (/home/sean/data-reports/node_modules/axios-auth-refresh/dist/index.min.js:1:1718)
    at /home/sean/data-reports/node_modules/axios-auth-refresh/dist/index.min.js:1:2719
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.GetFolderInfo (/home/sean/data-reports/server/nmcapi.js:29:29)
    at /home/sean/data-reports/server/interval.js:25:18
    at async Promise.all (index 0)
    at Object.intervalFunc (/home/sean/data-reports/server/interval.js:36:18)
  axios POST /auth/login/ +16ms
  axios 200 OK (POST https://api.example.com/api/v1.0/auth/login/) +561ms
Auth token: 17412724ef5169eaab8502a9851480741e606ffa

As far as I can tell, the refreshAuthLogic function is working properly (because it returns a new auth token), but everything stops after that.
What am I missing?

**Comment by Flyrell** [comment]
Hi, the `refreshAuthLogic` function should return the request `instance.post(...).then(...)`. You're not returning anything it that function, so the library doesn't have any refresh call to bind to. So it should look as follows:

```javascript
const refreshAuthLogic = (failedRequest) => {
    return instance
        .post('/auth/login/', {
            username: process.env.USER,
            password: process.env.PASS,
            skipAuthRefresh: true,
        })
        .then((tokenRefreshResponse) => {
            failedRequest.response.config.headers.Authorization = `Token ${tokenRefreshResponse.data.token}`;
            return Promise.resolve();
        });
};
```

And if you're calling the refresh login with `{ skipAuthRefresh: true }` it's doesn't do anything unless you use it with `skipWhileRefreshing` flag. That's because the plugin automatically stalls all the requests in axios instance you provided to prevent the loop (in case someone forgets to provide the `skipAuthRefresh` to the refreshing call). This behaviour may change in the future releases, but for now you should also use the `skipWhileRefreshing` flag.

```javascript
axiosauthrefresh.default(instance, refreshAuthLogic, { skipWhileRefreshing: true });
```

**Comment by wipash** [comment]
Ah, amazing, thank you so much! It was indeed something obvious, sorry for using your time =]

**Comment by tibbe** [comment]
@Flyrell how does this look like in a scenario using `await`? Just

```js
const refreshAuthLogic = (failedRequest) => {
    const tokenRefreshResponse = await instance
        .post('/auth/login/', {
            username: process.env.USER,
            password: process.env.PASS,
            skipAuthRefresh: true,
        });
    failedRequest.response.config.headers.Authorization = `Token ${tokenRefreshResponse.data.token}`;
};
```

Or does something else need to be returned?
