### ISSUE TITLE
GET query invoked with a previous token after 401

### ISSUE THREAD

**Issue by whity-art** [Flyrell/axios-auth-refresh#86]
Hi guys,

Library works fine. But I have one problem. 
There is one GET requests, that I have to resend after it return 401. 

It looks like:

axios.get(`http://someUrl/check_token?token=${getToken()}`)

In general, it looks like when I call the query I get the current token from localStorage. It works if token is valid, but if it returns 401 and if the library invokes the query again, it pass the old token. 
The function is not called again in order to get new token. 

Do you have any ideas on how to do it to always have a fresh token?

Thanks for any help.

Regards.

**Comment by Flyrell** [comment]
Well, this happens because when the token is refreshed, the last request is just retried from the error configuration that axios provides. It does not trigger any logic as it was already triggered before making the first request. 

```javascript
const data = await axios.get(`http://someUrl/check_token?token=${getToken()}`);
/**
 * Before running the actual axios.get method, the above line gets evaluated to:
 * const data = await axios.get('http://someUrl/check_token?token=some-token');
 */

/**
 * The call returns 401, so the library takes it from here...
 *   1. `refreshAuthLogic` function gets called
 *   2. After refreshing, the error config (with the previously evaluated URL) gets called again.
 *      As the token is not bound dynamically, the URL still has the old token as the query parameter.
 */
```

There is few ways (I can think of) you can accomplish what you're looking for:

1. Use interceptor to bind the token as a query parameter dynamically. Although it would work, it might be a bit too much logic for what you're trying to accomplish, especially when it's only for one request (as it runs before every request).
```javascript
const data = await axios.get('http://someUrl/check_token?token={token}');
axios.interceptors.request.use(config => config.url.replace('{token}', getToken()));
```

2. In the `refreshAuthLogic` function there is an error object available for you. You can replace the query parameters after refreshing the token.
```javascript
// Library initialization
createAxiosAuthRefresh(axios, async (errorConfig) => {
  const response = await axios.post('https://someUrl/refresh_auth');
  setToken(response.data.token); // this would be your usual logic to set the token globally
  errorConfig.params.token = response.data.token; // this would replace the parameters in the retried requrest
});

const data = await axios.get(`http://someUrl/check_token?token=${getToken()}`);
```
 
I haven't tested any of this, but it should work with a little bit of polishing. At least I hope you get the idea.

**Comment by Flyrell** [comment]
Hope that helped. Please, use StackOverflow for the future implementation related questions :nerd_face:
