### ISSUE TITLE
Not all pending calls are retried if multiple calls return 401

### ISSUE THREAD

**Issue by JWess** [Flyrell/axios-auth-refresh#90]
In my React app, when a particular component is activated, I immediately use Axios to make three independant API calls. When my token is expired, all three calls return 401 as expected. As soon as one of the calls returns a 401, the refresh interceptor kicks off a call to refresh the token. When the refresh call succeeds, the original call is retried, but the other two original failing calls are not retried. **It seems like any calls that return 401's while the refresh is happening should be retried after the refresh succeeds.** I expected this library to already handle this. Perhaps it does, and I'm misinterpreting what I'm seeing? Any guidance/feedback would be very much appreciated.

**Comment by JWess** [comment]
Here is an implementation in Angular that uses an RxJS BehaviorSubject as a semaphore to block and release requests during the refreshing.

https://angular-academy.com/angular-jwt/#refresh-token

**Comment by Flyrell** [comment]
Hi, thanks for opening the issue. This will be the default behaviour in the next major version.

For now, check the `skipWhileRefreshing` option, please. Library by default prevents refreshing from multiple simultaneous calls to not enter the interceptor-loop in case any of them return 401 again. You can turn off the `skipWhileRefreshing` option while initialising the interceptor and use `skipAuthRefresh` flag for refreshing request to prevent that behaviour manually.

**Comment by JWess** [comment]
Glad to hear that will be the default behavior in the future. Perhaps `skipWhileRefreshing` should be renamed to something like `queuePendingCallsWhileRefreshing` or something like that. While I did read through the README, I never considered that `skipWhileRefreshing` would get me the behavior that I was seeking.

**Comment by Flyrell** [comment]
Yeah, that I agree with.

**Comment by nmkae** [comment]
Hi, I've encountered a similar issue but have had no luck so far getting it to work with `skipWhileRefreshing: false` while not spamming calls afterwards.

**Comment by romonsalve** [comment]
> Hi, I've encountered a similar issue but have had no luck so far getting it to work with `skipWhileRefreshing: false` while not spamming calls afterwards.

Remember that skipWhileRefreshing is an interceptor option. 
You need to set on createAuthRefreshInterceptor

I was using it like an axios request option the first time, maybe your doing the same

**Comment by Flyrell** [comment]
Yes, `skipWhileRefreshing` option needs to be set when initialising the interceptor. Then, as `skipWhileRefreshing` flag is stopping the default prevention from interceptors' loop, you should set `skipAuthRefresh` flag to any request that you're calling from the refreshing function in order for the library to know that this request is a process of refreshing and if it fails again, it should not be retried.

The `skipWhileRefreshing` flag has an unfortunate name and I apologise for that. In case you're wondering why the library works like that at all, here's the quick explanation:

> When I created the library, I wanted it to be implemented as easy as possible. I believed that the authentication process which runs in the callback function (called `refreshAuthLogic` in docs) may not always be dependent on an API call, and also, I believed developers may not always read the docs and implement something like `skipAuthRefresh` flag to the refreshing calls (which is why it was not implemented at all in the first few versions). Because of that belief, pausing the whole instance seemed like a good idea to prevent any kind of unexpected bugs with interceptor loops, when the authentication logic fails.

It turns out I was wrong, more and more developers use the `skipWhileRefreshing` option to disable the default prevention. Of course, I don't know if they use `skipAuthRefresh` flag afterwards in order to prevent the interceptor loops (hope they are), but it seems like a good idea to remove it or at least make it easier to implement.

So the plans for the future of this library are quite simple. I will try to figurate out an easy and safe way to disable the default prevention mechanism and will probably leave it up to developers to use flag `skipAuthRefresh` on their calls while refreshing, to prevent the loop. I would also like to find a way to, at least, warn the developers who do not use the flag and/or create the fallback to default prevention mechanism in that case. But, to be honest, I'm not sure if there's a way to do that without any crazy logic. Of course, any help would be much appreciated. Also, might be worth to mention that this would surely introduce a breaking change, so expect this to be in version 3.x.x.

**Comment by FatehAK** [comment]
Any updates on this facing the same issue. Maybe you could document an example with the `skipWhileRefreshing` flag for the time being. Thanks

**Comment by theMasix** [comment]
@Flyrell I use my implemented ```axiosInstance``` that used in the whole app and pass it to ```createAuthRefreshInterceptor``` to catch 401 status code. Then use plain ```axios``` to use in ```refreshAuthLogin``` func. So if the ```axios``` in refreshAuthLogin``` fails again, another trying shouldn't happen.
I think it might prevent infinite loop. doesn't?

**Comment by Flyrell** [comment]
This change will be published in v3.0.0 [PR #105]. I hope to publish it soon.

**Comment by niqitosiq** [comment]
Using the 
```
const [slider, package, banner, announcement] = await Promise.all([
      app.$api.widget.slider(),
      app.$api.widget.package(),
      app.$api.widget.banner(),
      app.$api.widget.announcement(),
]);
```
for fetch data, together with `skipWhileRefreshing: false`, refresh requests fail:
![изображение](https://user-images.githubusercontent.com/15576320/89535179-18c29f00-d807-11ea-97b0-e580776426af.png)
Is there anything you can do about this?

**Comment by Flyrell** [comment]
@niqitosiq sorry I must have overlooked your comment in e-mails. How are you binding the token? If you use the interceptor to bind the newest token dynamically this shouldn't be an issue, as each "repeated" request should get newest token.

Example:
```javascript
// Obtain the fresh token each time the function is called
function getAccessToken() {
    return localStorage.getItem('token');
}

// Use interceptor to inject the token to requests
axios.interceptors.request.use(request => {
    request.headers['Authorization'] = `Bearer ${getAccessToken()}`;
    return request;
});
```

**Comment by niqitosiq** [comment]
Thank you, now all is working.
I have used
```config.headers.common['Authorization'] = ...```
instead
```config.headers['Authorization'] = ...``` 😅

**Comment by Flyrell** [comment]
Version v3.0.0 is now out and should deal with the issue discussed here. See [change-log section](https://github.com/Flyrell/axios-auth-refresh#changelog) section to see what's changed. Feel free to reopen if the issue persists.
